name: edu_guard
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  image_picker: ^1.0.4
  flutter_riverpod: ^2.4.8
  http: ^1.1.0
  expandable_text: ^2.3.0
  expandable: ^5.0.1
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  flutter_cache_manager: ^3.3.1
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  jwt_decode_full: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/health_insurance.jpg
    - asset/images/travel_insurance.jpg
    - asset/images/smile.jpg
    - asset/images/mtn_logo.png
    - asset/images/eduguard_logo_01.png
    - asset/images/eduguard_logo_02.png
    - asset/doc/Flutter_Courses_Structure.docx
    - asset/icon/
    - assets/image/flag/
    - assets/icon/
    - assets/logo/
    - assets/image/
    - assets/images/
    - assets/doc/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
